#include "le_compiler.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char* read_file(const char* path){
    FILE* f=fopen(path,"rb"); if(!f)return NULL;
    fseek(f,0,SEEK_END); long len=ftell(f); fseek(f,0,SEEK_SET);
    char* b=(char*)malloc((size_t)len+1); (void)fread(b,1,(size_t)len,f); b[len]=0; fclose(f);
    return b;
}
int main(int argc, char** argv){
    if(argc<4){printf("usage: %s <circuit.json> <out.lebin> <out.h>\n",argv[0]); return 1;}
    char* js=read_file(argv[1]); if(!js){printf("no circuit\n");return 1;}
    le_compiler_options_t o=le_compiler_options_init(LE_OPT_NONE);
    le_compile_result_t r; memset(&r,0,sizeof(r));
    int rc=le_compile_json_ex(js,NULL,&o,&r);
    if(rc!=0||!r.success){printf("compile failed rc=%d %s\n",rc,r.error_message?r.error_message:"");return 1;}
    /* write .lebin */
    FILE* b=fopen(argv[2],"wb"); fwrite(r.binary_data,1,r.binary_size,b); fclose(b);
    /* write .h */
    FILE* h=fopen(argv[3],"w");
    fprintf(h,"/* Auto-generated by regen_example.c - DO NOT EDIT */\n");
    fprintf(h,"#ifndef LE_DEFAULT_PROGRAM_H\n#define LE_DEFAULT_PROGRAM_H\n");
    fprintf(h,"#include <stdint.h>\n");
    fprintf(h,"// Compiled from %s (LEB1), %zu bytes, %d instructions\n",
            argv[1], r.binary_size, r.instruction_count);
    fprintf(h,"static const uint8_t le_default_program[%d] = {", (int)r.binary_size);
    for(int i=0;i<(int)r.binary_size;i++){
        if(i%16==0) fprintf(h,"\n    ");
        fprintf(h,"0x%02X%s", r.binary_data[i], i==(int)r.binary_size-1?"":", ");
    }
    fprintf(h,"\n};\n");
    fprintf(h,"#endif /* LE_DEFAULT_PROGRAM_H */\n");
    fclose(h);
    printf("OK instructions=%d size=%zu\n", r.instruction_count, r.binary_size);
    le_compile_result_free(&r);
    return 0;
}